# Generated by Django 3.1.3 on 2020-12-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('h', models.DecimalField(decimal_places=1, max_digits=5)),
                ('b', models.DecimalField(decimal_places=1, max_digits=5)),
                ('s', models.DecimalField(decimal_places=1, max_digits=3)),
                ('t', models.DecimalField(decimal_places=1, max_digits=3)),
                ('r_1', models.DecimalField(decimal_places=1, max_digits=3)),
                ('r_2', models.DecimalField(decimal_places=1, max_digits=3)),
                ('A', models.DecimalField(decimal_places=2, max_digits=6)),
                ('P', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Iy', models.DecimalField(decimal_places=3, max_digits=10)),
                ('Wy', models.DecimalField(decimal_places=3, max_digits=10)),
                ('Sy', models.DecimalField(decimal_places=3, max_digits=10)),
                ('i_y', models.DecimalField(decimal_places=1, max_digits=4)),
                ('Iz', models.DecimalField(decimal_places=3, max_digits=10)),
                ('Wz', models.DecimalField(decimal_places=3, max_digits=10)),
                ('Sz', models.DecimalField(decimal_places=3, max_digits=10)),
                ('i_z', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
        ),
    ]
